[package]
name = "albumark"
version = "0.5.0"
description = "辑印 Albumark —— 轻量、本地优先的图像批量水印与快速辑录工具"
authors = ["MogroWang Studio"]
edition = "2021"

[lib]
name = "albumark_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-http = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
trash = "5"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
